import os
import json
from datetime import datetime

LOGS_DIR = "logs"

def ensure_logs_dir():
    if not os.path.exists(LOGS_DIR):
        os.makedirs(LOGS_DIR)

def generate_log(data=None):
    ensure_logs_dir()
    
    # Δημιουργεί πάντα μοναδικό αρχείο (ώστε να έχει commit κάθε φορά)
    timestamp = datetime.utcnow().strftime("%Y-%m-%d_%H-%M-%S")
    filename = f"thursday_{timestamp}.json"
    filepath = os.path.join(LOGS_DIR, filename)

    # Απλό test log (αν δεν δίνεται custom data)
    if data is None:
        data = {
            "status": "Thursday Analysis completed successfully!",
            "timestamp": timestamp,
            "note": "Auto-generated by Bombay Logger"
        }

    with open(filepath, "w") as f:
        json.dump(data, f, indent=2)
    
    print(f"[Bombay Logger] Log file created: {filepath}")
    return filepath


if __name__ == "__main__":
    generate_log()
